title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: green
  header:
    title: Mike Harding
    tagline: >-
      CS Student at Utah Valley University. Favorite programming language is
      Rust.
    profile_img: >-
      https://res.cloudinary.com/practicaldev/image/fetch/s--OksKss_K--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/2205/gM7pbalI.jpg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
      - text: Made with Stackbit
        url: "https://www.stackbit.com"
        new_window: true
disableKinds:
  - RSS
